#!/usr/bin/python -u
#
# CS3700, Northeastern University
# Project 3 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json
from string import ascii_letters, digits, punctuation
import dns_packet

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

# Do not change this function!
def chunks(packet):
  for i in xrange(0, len(packet), 16):
    yield packet[i:i+16]

# Do not change this function!
def toascii(char):
  if char == "  ":
    return ""
  if char in ascii_letters or char in digits or char in punctuation or char == ' ':
    return char
  return '.'

# DUMP THE PACKET
# Do not change this function!
def dump_packet(packet):
  lineno = 0
  for line in list(chunks(packet)):
    larr = list("{:02X}".format(ord(x)) for x in line)
    while len(larr) < 16:
      larr.append("  ")

    r = "[%04x]   " % (lineno)
    r = r + " ".join(larr[0:8]) + "   "
    r = r + " ".join(larr[8:16]) + "   "
    r = r + ("".join(toascii(x) for x in line[0:8]))
    if len(line) > 8:
      r = r + " " + ("".join(toascii(x) for x in line[8:16]))
    lineno += 16
    print r

TIMEOUT = 5
MSG_SIZE = 1500

# Bind to all addresses and an ephemeral port
UDP_IP = ""
UDP_PORT = 0
  
# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]

  
# Check to make sure command line arguements were passed correctly
if(len(sys.argv) != 3):
    print "Usage: ./3700dns @<server:port> <name>"
    sys.exit(-1)

request = dns_packet.create_request(sys.argv[2])
dump_packet(request)

#print binascii.hexlify(bytearray(request))

# Send the packet to the DNS server (you'll need to parse the args)
ip = sys.argv[1]
tmp = ip.split(':')
if(len(tmp) == 2):
    port = tmp[1]
else:
    port = 53

ip = tmp[0]
ip = ip.replace("@", "")

print "ip = " + str(ip)
print "port = " +str(port)
sock.sendto(request, (ip, port))

# Now wait for response 
result = sock.recvfrom(MSG_SIZE)
  
# If nothing is ready, we hit the timeout
if result:
  (data, addr) = result
  decoded_packet = dns_packet.decode_answer(data)
    
#  print str(decoded_packet.ancount) + " answer"

 # Very the question matches what was send
#  if(dns_packet.verify_question(data[:12], request)):
#      
#   else:
#       print "ERROR received question does not match sent message"
#
  


 # for i in range(0, decoded_packet.ancount):
 #     answer = dns_packet.get_answer(data[12:])


  # Process the response, print out results
#else:
#  log("[error] timeout")
#  sys.exit(-1)
#
